### PR TITLE
Issue78

### PR DESCRIPTION
**Pull request by Hendricxw**
Just the timestamp in the table is not really nice, besides, all bugs are fixed.

### CODE REVIEW

**Comment by elma13** [comment]
@Hendricxw , I tested the code in Rstudio, and if I go directly to the Metadata tab and select on the map, then this error:

image

In the final approach, the sensors only appear on the map if there is data, so maybe then this problem is vanished?

**Comment by elma13** [comment]
@Hendricxw , it is not clear to me what bugs you fixed in this issue. The table is still outside the div.
image

**Comment by elma13** [comment]
@Hendricxw , there are still some print-statements in the code. If they are usefull for debug, please use the logger-function.

**Comment by Hendricxw** [comment]
Apparently this is only working for a big screen... Besides, user input on the selected data-range is needed for the table. Alternatively, we could use the max/min of the dataframe itself

**Review by elma13 — CHANGES_REQUESTED** [review]
@Hendricxw, if no data available then this warning: 
image

Could you add a validate(need()) ?

**Comment by elma13** [comment]
> Apparently this is only working for a big screen... Besides, user input on the selected data-range is needed for the table. Alternatively, we could use the max/min of the dataframe itself

Hmm, that is a pity. Let's try to fix that later, if the other elements of the tool are working. And we had a first users feedback.

**Pull request merged**
