### PR TITLE
Added data prep

### PR DESCRIPTION
**Pull request by jspijker**
Added data prep script and separate script for installing packages etc. See #1

### CODE REVIEW

**Comment by elma13** [comment]
For #1 could you select the pm10_kal and pm25_kal, instead the raw values?


And for a estimation of the uncertainty of the sensors an average value could be interesting. Can you add it to the data_prep?


What about the reference and the knmi data? Do we start without them and add them later?

**Comment by jspijker** [comment]
Calibrated pm10 and pm25 added. Calculation of averages (averaged over time) added as new dataset. See [b525297](https://github.com/rivm-syso/Analyse-Together/pull/2/commits/b5252970b5a37c2c6c11d635d6c40e79b33de41e)

KNMI stations are already available in the _raw data.

**Comment by elma13** [comment]
Nice to have the sensor measurements, what about the meta data (including location)? Do we already have a data structure for that? And in what format do we have the KNMI and reference data?

**Comment by jspijker** [comment]
Not relevant anymore, removed, also closes #1

**Pull request closed without merging**
